language: python

python:
  - 3.4
  - 3.3
  - 3.2
  - 2.7
  - 2.6

# command to run tests
script:
  - apt-get install rabbitmq-server
  - apt-get install python-pip
  - pip install -r requirements.txt
  - python test_integration.py
  - [ $(rabbitmqctl list_queues -q) == "publisher-test-queue	1" ] || exit 1
