language: python

python:
  - 2.7
  - 2.6

# command to run tests
script:
  - git clone https://github.com/openstack/ceilometer.git ../ceilometer
  - pip install -r requirements.txt
  - pip install -r ../ceilometer/requirements.txt
  - pip install ../ceilometer
  - python test_integration.py
