language: python

python:
  - 2.7
  - 2.6

# command to run tests
script:
  - sudo apt-get install rabbitmq-server
  - sudo apt-get install python-pip
  - sudo pip install -r requirements.txt
  - cd ..
  - git clone https://github.com/openstack/ceilometer.git
  - cd ceilometer
  - sudo pip install -r requirements.txt
  - sudo python setup.py install --prefix='~/virtualenv'
  - cd ../ceilometer-publisher-rabbitmq
  - python test_integration.py
