language: python

python:
  - 3.4
  - 3.3
  - 3.2
  - 2.7
  - 2.6

# command to run tests
script:
  - sudo apt-get install rabbitmq-server
  - sudo apt-get install python-pip
  - sudo pip install -r requirements.txt
  - git clone https://github.com/openstack/ceilometer.git
  - cd ceilometer
  - sudo pip install -r requirements.txt
  - sudo python setup.py install
  - cd ..
  - python test_integration.py
  - "[ $(rabbitmqctl list_queues -q) == \"publisher-test-queue	1\" ] || exit 1"
